### ISSUE TITLE
关于DEAP中EEG数据的细节问题

### ISSUE THREAD

**Issue by logicvanlyf** [xbrainnet/CAFNet#12]
您好，我想问一下，DEAP数据集中的EEG数据是使用bdf文件中所有时间长度，还是和MAHNOB一样，选取最后30s的EEG数据，还是有另外的处理选择的方式？

**Comment by logicvanlyf** [comment]
您好，在DEAP数据集中，每个trial的长度应为60s，一共有40个trial。但是在原始bdf文件中，每个人只有1个bdf文件。我想问这是如何进行切分的？

**Comment by kaio-99** [comment]
DEAP数据集直接使用每个trial的所有长度，即为60s；
DEAP数据集同样提供了经过预处理的数据，即data_preprocessed_matlab或data_preprocessed_python，其中每个文件的数据维度为40x40x8064（trial x channel x timepoints），你可以根据需求选取前32个脑电通道，并移除前3s数据，最终得到40x32x7680的数据，然后再借助MNE库来进行PSD特征提取和时间窗口划分

**Comment by logicvanlyf** [comment]
所以，作者你的意思是，对于deap数据集，您使用的是data_preprocessed_python这个文件夹下的数据文件做处理的，而没用原始original bdf文件，是这样吗？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月29日 10:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xbrainnet/CAFNet] 关于DEAP中EEG数据的细节问题 (Issue #12) |

DEAP数据集直接使用每个trial的所有长度，即为60s；
DEAP数据集同样提供了经过预处理的数据，即data_preprocessed_matlab或data_preprocessed_python，其中每个文件的数据维度为40x40x8064（trial x channel x timepoints），你可以根据需求选取前32个脑电通道，并移除前3s数据，最终得到40x32x7680的数据，然后再借助MNE库来进行PSD特征提取和时间窗口划分

**Comment by kaio-99** [comment]
> 所以，作者你的意思是，对于deap数据集，您使用的是data_preprocessed_python这个文件夹下的数据文件做处理的，而没用原始original bdf文件，是这样吗？
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年05月29日 10:43 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [xbrainnet/CAFNet] 关于DEAP中EEG数据的细节问题 (Issue #12) | DEAP数据集直接使用每个trial的所有长度，即为60s； DEAP数据集同样提供了经过预处理的数据，即data_preprocessed_matlab或data_preprocessed_python，其中每个文件的数据维度为40x40x8064（trial x channel x timepoints），你可以根据需求选取前32个脑电通道，并移除前3s数据，最终得到40x32x7680的数据，然后再借助MNE库来进行PSD特征提取和时间窗口划分 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

是的，对于deap数据集，由于原始的bdf数据没有经过切分，因此需要使用处理后的data_preprocessed_python进行进一步预处理

**Comment by jianghaisi** [comment]
那是不是每个受试者后面处理的特征是40*32*20*5，如有回答，感激不尽

**Comment by kaio-99** [comment]
> 那是不是每个受试者后面处理的特征是40_32_20*5，如有回答，感激不尽

你好，是的
