### ISSUE TITLE
About deap dataset preprocessing

### ISSUE THREAD

**Issue by ldxbxl** [xbrainnet/CAFNet#3]
After browsing the code, I found that the two inputs and labels of deap were processed into numpy arrays. Could you please tell me how to get from the original deap data set to these three arrays? Could you please provide the relevant codes? Looking forward to your reply, thank you very much.

**Comment by kaio-99** [comment]
This issue is answered in [https://github.com/xbrainnet/CAFNet/issues/4](url)
