### ISSUE TITLE
do you use the bdf file in the original data？

### ISSUE THREAD

**Issue by logicvanlyf** [xbrainnet/CAFNet#6]
Hello, when you process EEG data, do you use the bdf file in the original data source set (take the DEAP dataset as an example)?

**Comment by kaio-99** [comment]
Yes, the original bdf file is used for further pre-processing, including downsampling, re-reference, etc.

**Comment by logicvanlyf** [comment]
感谢您的回复。我在github上又咨询了几个问题，贵团队有时间能够解答一下吗？如果您能回复解答，我将不胜感激。



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/13/2024 10:47 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [xbrainnet/CAFNet] do you use the bdf file in the original data？ (Issue #6) |

Yes, the original bdf file is used for further pre-processing, including downsampling, re-reference, etc.
