### ISSUE TITLE
About DEAP dataset label.npy file

### ISSUE THREAD

**Issue by logicvanlyf** [xbrainnet/CAFNet#8]
self.parser.add_argument('--path_label', type=str, default='data\\label2.npy', help='path of label. Valence——label1; Arousal——label2')

Hello, as the above code, what file is label.npy used and how to deal with it. If you can answer, I would be very grateful.

**Comment by kaio-99** [comment]
在您下载数据后，您应该也能够获取数据相应的metadata zip文件，其中包含participant_ratings文件，文件中表明了每位受试者在观看每个视频后对情绪的打分

**Comment by logicvanlyf** [comment]
您好，github我又咨询了一些问题，贵团队方便回答吗？如能回复，不胜感激



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月15日 15:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xbrainnet/CAFNet] About DEAP dataset label.npy file (Issue #8) |

在您下载数据后，您应该也能够获取数据相应的metadata zip文件，其中包含participant_ratings文件，文件中表明了每位受试者在观看每个视频后对情绪的打分
